### ISSUE TITLE
Can't install app in Sandbox

### ISSUE THREAD

**Issue by jamescary** [SalesforceLabs/ForecastingMobileUI#1]
Trying to install Collaborative Forecasting in my company's FULL sandbox org but am getting an error on install to all users... Not sure how to pinpoint the issue to fix this problem with the install. Here is the error:

This app can't be installed.
There are problems that prevent this package from being installed.
Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem OppsInForecastCategoryController: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem ForecastAttainmentModel: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem ForecastingTypeUtil: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

![forecastingitemerror](https://cloud.githubusercontent.com/assets/1034025/7638475/26a58f44-fa43-11e4-99fd-7697d26102f3.PNG)

**Comment by alonkama** [comment]
I'm suspecting bad data in that Sandbox org, but am not sure. 
Can you run a report or query on ForecastingItem ? Maybe group by ForecastCategoryName? That is the the only restricted picklist on that object.

Sometimes these error messages have nothing to do with the underlying cause. But if you have this successfully installed in production and it's only giving problems in Sandbox, it may be due to partial sandbox copy.

**Comment by jamescary** [comment]
Hi Alon,
I've an extract for ForecastingItem sorted by ForecastCategoryName here:
https://www.dropbox.com/s/y4u56x8ekwioppb/forecastingitem_export.csv?dl=0

Having trouble installing this to both our Production and Full copy sandbox orgs and this error message is still puzzling me totally. Thanks for any suggestions or support you can offer.

**Comment by alonkama** [comment]
James, I did more digging. It looks to be a generic Salesforce package installation issue. I checked the logs and unfortunately you're the only customer hitting it. I suggest you log a case and reference StackTraceId-1626833660.
Please let me know how it goes - I'm curious what the resolution will be.

**Comment by alonkama** [comment]
@jamescary I found out that the issue is related to having Historical Trending enabled for Forecasting. If it's possible to disable it in your sandbox, please retry the installation of this package.
